### PR TITLE
Support nested map set

### PR DESCRIPTION
**Pull request by nc**
Quick hack to unblock progress in using this library for now. Ideally we don't do a deep compare everytime a value on `p` changes.

### CODE REVIEW

**Comment by dai-shi** [comment]
Yeah, I feel like deepEqual is unavoidable. Would you clean up the code and I will do final review.

**Comment by nc** [comment]
@dai-shi yep, ready for review.

**Review by dai-shi — APPROVED** [review]
Thanks for your contribution! Free feel to continue if you get a better idea.

**Comment by dai-shi** [comment]
Published: https://www.npmjs.com/package/valtio-yjs/v/0.1.5

**Pull request merged**
